[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Testing
fuzz = { runs = 256 }
invariant = { runs = 256 }

[profile.default.fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "single"

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
amoy = "${AMOY_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }
amoy = { key = "${POLYGONSCAN_API_KEY}" }
